# Generated by Django 6.0.3 on 2026-03-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_recurringpersonalevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshift",
            name="color_hex",
            field=models.CharField(default="#10b981", max_length=7),
        ),
    ]
