# Generated by Django 6.0.3 on 2026-03-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workshift_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalevent',
            name='color_hex',
            field=models.CharField(default='#FCAF17', max_length=7),
        ),
    ]
