# Generated by Django 6.0.4 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_personalevent_color_hex"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringworkshift",
            name="recurrence_pattern",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Every 2 Weeks"),
                    ("monthly", "Monthly"),
                ],
                default="weekly",
                max_length=20,
            ),
        ),
    ]
