# Generated by Django 6.0.4 on 2026-04-17 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workshift_schedule_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadAnalysis',
            fields=[
                ('analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('week_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_class_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_assignment_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('available_study_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('utilization_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('week_status', models.CharField(blank=True, choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=10)),
                ('assignment_count', models.IntegerField(blank=True, null=True)),
                ('major_assignment_count', models.IntegerField(blank=True, null=True)),
                ('deadline_cluster_detected', models.BooleanField(default=False)),
                ('is_overloaded', models.BooleanField(default=False)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start_date'), name='unique_user_week_start_workload_analysis')],
            },
        ),
    ]
