# Generated by Django 6.0.4 on 2026-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_workloadanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalevent",
            name="color_hex",
            field=models.CharField(default="#8B5CF6", max_length=7),
        ),
        migrations.AlterField(
            model_name="workshift",
            name="color_hex",
            field=models.CharField(default="#10B981", max_length=7),
        ),
    ]
